[package]
name = "audio_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
rfd = "0.16.0"
eframe = "0.33.3"
egui_plot = "0.34.0"

# デコード（MP3/FLAC）+ 形式/タグ情報
symphonia = { version = "0.5", default-features = false, features = ["mp3", "flac"] }

# FFT
rustfft = "6"

# リサンプル（比較しやすくする用：48kHzに合わせる）
rubato = "0.16.2"
